### ISSUE TITLE
README - commands that include `-m reactive` give errors

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/cos-proxy-operator#11]
I am trying to follow the steps in the README to get cos-proxy up and running but it seems that the commands including `-m reactive` don't work out of the box. I need to manually switch to the reactive model for them to work (and then, they also work without the `-m reactive` argument of course).

![image](https://user-images.githubusercontent.com/6230162/153631730-f9839602-0d73-4547-8b07-2147bbb42a44.png)

Also, to consume the cross-model relation I have to juju switch to the reactive controller and do:
`j consume microk8s:admin/cos.prometheus`

Otherwise:
![image](https://user-images.githubusercontent.com/6230162/153632055-5d5fa9b2-2196-4ac1-aa67-1091fa48c3c1.png)

Might be more problems later on, I didn't get there yet. Will keep this updated.

**Comment by PietroPasotti** [comment]
`j offer grafana:grafana_dashboard`
ERROR cannot add application offer "grafana": getting relation endpoint for relation "grafana_dashboard" and application "grafana":
application "grafana" has no "grafana_dashboard" relation

**Comment by PietroPasotti** [comment]
`j offer grafana:grafana_dashboard` --> `j offer grafana:grafana-dashboard`

**Comment by PietroPasotti** [comment]
`juju relate -m reactive grafana cos-proxy:downstream-grafana-dashboard**s**` --> `juju relate -m reactive grafana cos-proxy:downstream-grafana-dashboard`

**Comment by PietroPasotti** [comment]
Also noticed that until I `j relate telegraf:dashboards cos-proxy:dashboards`, the cos-proxy will report a blocked status with status message: "one of (Grafana|dashboard) relation missing" (or something like that).
Would be more helpful if it said "(Grafana|dashboard**s**)"

**Comment by rbarry82** [comment]
This is based on the assumption that there's a Juju controller which manages both clouds rather than two separate controllers. I'll update the `README` to reflect thi.
