### ISSUE TITLE
Severity is not calculated correctly, when metrics are absent

### ISSUE THREAD

**Issue by err404r** [canonical/cos-proxy-operator#146]
### Bug Description

In https://github.com/canonical/cos-proxy-operator/issues/98 severity was introduced to metrics rules.

However there is a small bug in them. When metrics is absent over time. the value became equal to one. Which means severity became warning.

And this shouldn't be like that. We could easily miss that node goes down. Because usually we are not sending warnigs to pagerduty

### To Reproduce

1. Deploy cos proxy
2. Put unit down
3. Alert in AlertManager will have warning severity

### Environment

-

### Relevant log output

```shell
-
```

**Comment by lucabello** [comment]
We should adjust the way we calculate the severity for that rule.

**Comment by sed-i** [comment]
Reference: https://github.com/canonical/cos-proxy-operator/pull/101/files
