### ISSUE TITLE
NRPE metrics not properly exported

### ISSUE THREAD

**Issue by simskij** [canonical/cos-proxy-operator#25]
When the cos-proxy is related to a nrpe-external-master, the nrpe_exporter is only exporting internal prometheus metrics, rather than the full nrpe check results.

The target is visible in Prometheus, and labelled correctly, but the actual relevant metrics are not available.

**Comment by aieri** [comment]
to give extra clarity, the prometheus `/targets` page lists all expected endpoints (e.g. `juju_openstack_666cbd0_bootstack_<cloudname>_aodh_2_check_crm_status_prometheus_scrape (1/1 up)`, but the actual endpoint `/metrics` page only has `go_*`, `process_*`, and `promhttp_*` metrics. I don't see the actual nrpe check output.
