### ISSUE TITLE
Add support for scrape interval and scrape timeout.

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-proxy-operator#29]
### Enhancement Proposal

Services configured by cos-proxy in prometheus has a default scrape_interval of 1m and a default scrape timeout of 10 seconds. These intervals may not be appropriate for nrpe checks that are usually executed every 5 minutes by Nagios with a timeout of 30 seconds.

The default intervals may generate overload on the units being monitored and false negative. 

The scrape interval should default to 5m
The scrape timeout should default to 30s

Also as an operator I would like them to be configurable to handle corner cases.

**Comment by dstathis** [comment]
Hello,

I will discuss making this change with the team. It seams like a reasonable suggestion.

If you need this functionality immediately, you should be able to use the [prometheus-scrape-config charm](https://charmhub.io/prometheus-scrape-config-k8s) to set the scrape interval.

**Comment by rbarry82** [comment]
The difficulty with the "corner cases" is somewhat scoping them. We could have a key such as `nrpe_scrape_interval` or similar (so it would not clobber "normal" Prometheus scrapes), as long as we have an idea of what a reasonable default is, but we'd pretty much need to know:

* What are good defaults?
* Is this only for NRPE? Less granularity ("all" scrape jobs) escalates rapidly. More granularity (only this or that job) also escalates rapidly, and would be better served by a second proxy related to `prometheus-scrape-config` (or similar) which only manages the isolated jobs

**Comment by simskij** [comment]
This should be done using `prometheus-scrape-config` rather than being a config option on the proxy itself. Closing without action.
