### ISSUE TITLE
Add nrpe unit name label to the metrics exported by the nrpe exporter

### ISSUE THREAD

**Issue by mert-kirpici** [canonical/cos-proxy-operator#33]
### Enhancement Proposal

Currently the metrics exported by the nrpe exporter have the label `juju_application` which contains the value of the `nrpe` application, however there's no way of knowing which unit of the application the check is related to.

This might be a useful label to utilize in the summary section of the firing alert to give the operator a pre-built command to get the NRPE check message, which can not be proxied. Example(after calling `label_replace()` to get the `check` field):
`juju run-action --wait {{ $labels.juju_unit }} run-nrpe-check name={{ $labels.check }}`

The operator receiving the alert would just copy and paste the command in the terminal to run the check manually and read the NRPE check message.

**Comment by dstathis** [comment]
Just to clarify, do you want the unit of the npre application in the label?

**Comment by mert-kirpici** [comment]
Yes I meant the nrpe application unit. Sorry for the confusion as I have just realized the label `juju_unit` exists and contains the application unit that the check is run on.
