### ISSUE TITLE
Add severity label to support PD dynamic notifications

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-proxy-operator#98]
### Enhancement Proposal

All alerts coming from nrpe-exporter have an hardcoded severity set to critical.

In order to support [PagerDuty dynamic-notifications](https://support.pagerduty.com/docs/dynamic-notifications) would be beneficial if the status of the check is reflected into the severity label of the alert.

An nrpe check can have one of the following status code that needs to be translate to a severity label as following 

  - 0 = OK  -> this doesn't produce any alert
  
  - 1 = Warning -> severity=warning
  - 2 = Critical  -> severity=critical
  - 3 = Unknown -> severity=error

**Comment by lucabello** [comment]
This has been resolved by https://github.com/canonical/cos-proxy-operator/pull/101
